### ISSUE TITLE
没必要这样子,做好自己..如果觉得好用就用,不好用就别用,谢谢

### ISSUE THREAD

**Issue by zhnnnnn** [MJCIOS/MJCSegmentInterface#3]

**Comment by MJCIOS** [comment]
肯定是有人喊你来的吧...没必要这样...管好自己的东西就好,,好的东西,人家自然会用..谢谢

**Comment by zhnnnnn** [comment]
谁他么喊我来？？？你自己心里没点数？？Trending上天天霸屏？自己看一眼点星星的账号你脸不红？

**Comment by MJCIOS** [comment]
朋友,那也不能怪我,是我把我框架地址,发到开发群里的,,他们觉得好,才点个赞..怪我咯?

**Comment by zhnnnnn** [comment]
你就装吧。。全tm僵尸号

**Comment by loveuqian** [comment]
和其他同类型框架比起来有什么优点？
